In [35]:
import numpy as np
import torch
import torch.nn as nn

In [36]:
data = np.genfromtxt('iris_2D_demo.csv', delimiter=',', skip_header=1)
x_data = torch.from_numpy(data[:, 0:2])
y_data = torch.from_numpy(data[:, 2])
print(x_data)
print(y_data)

tensor([[1.4000, 0.2000],
        [1.5000, 0.2000],
        [3.0000, 1.1000],
        [4.1000, 1.3000]], dtype=torch.float64)
tensor([0., 0., 1., 1.], dtype=torch.float64)


In [37]:
linear = nn.Linear(2, 1)

linear.weight.data = torch.Tensor([[0.5, -0.1]])
linear.bias.data = torch.Tensor([0.1])

print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.5000, -0.1000]], requires_grad=True)
Parameter containing:
tensor([0.1000], requires_grad=True)


In [38]:
loss_fn = nn.BCELoss()
optimizer = torch.optim.SGD(linear.parameters(),
                            lr=0.01)
epochs = 1

In [39]:
# training
for epoch in range(epochs):
    for i in range (x_data.shape[0]):
        x = x_data[i].float()
        y = y_data[i: i+1].float()
        #y_hat
        y_hat = torch.sigmoid(linear(x))
        print(f'y_hat: {y_hat.item()}')
        # loss
        loss = loss_fn(y_hat, y)
        print(f'loss: {loss.item()}')

        #compute gradient
        optimizer.zero_grad()
        loss.backward()
        print(f'(dw, db): ({linear.weight.grad.data}, {linear.bias.grad.data})')

        #updata
        optimizer.step()
        print(f'(w, b): ({linear.weight.data}, {linear.bias.data})')


y_hat: 0.6856801509857178
loss: 1.1573442220687866
(dw, db): (tensor([[0.9600, 0.1371]]), tensor([0.6857]))
(w, b): (tensor([[ 0.4904, -0.1014]]), tensor([0.0931]))
y_hat: 0.6917833089828491
loss: 1.1769522428512573
(dw, db): (tensor([[1.0377, 0.1384]]), tensor([0.6918]))
(w, b): (tensor([[ 0.4800, -0.1028]]), tensor([0.0862]))
y_hat: 0.8042805790901184
loss: 0.2178070843219757
(dw, db): (tensor([[-0.5872, -0.2153]]), tensor([-0.1957]))
(w, b): (tensor([[ 0.4859, -0.1006]]), tensor([0.0882]))
y_hat: 0.8753998279571533
loss: 0.133074551820755
(dw, db): (tensor([[-0.5109, -0.1620]]), tensor([-0.1246]))
(w, b): (tensor([[ 0.4910, -0.0990]]), tensor([0.0894]))
