In [61]:
import numpy as np
import torch
import matplotlib.pyplot as plt
import pandas as pd

In [62]:
# df = pd.read_csv('data.csv')
data =np.genfromtxt('data.csv', delimiter=',', skip_header=0)
x_data = torch.from_numpy(data[:, 0:1])
y_data = torch.from_numpy(data[:, 1])
# y_data = df.iloc[:, 1].values
print(x_data)
print(y_data)

tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]], dtype=torch.float64)
tensor([9.1000, 5.9000, 4.6000, 6.7000], dtype=torch.float64)


In [63]:
# Create a Linear layer
linear = torch.nn.Linear(1,1)   # 1 feature 1 output

# Set value
linear.weight.data = torch.Tensor([[-0.34]])
linear.bias.data = torch.Tensor([0.04])

print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[-0.3400]], requires_grad=True)
Parameter containing:
tensor([0.0400], requires_grad=True)


In [64]:
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)
epochs = 1

In [ ]:
# training 
for epoch in range(epochs):
    for i in range(4):
        x = x_data[i].float()
        y = y_data[i].float()

        # predict
        y_hat = linear(x)
        print(f'y_hat: {y_hat.item()}')

        # compute loss
        loss = loss_fn(y_hat, y)
        print(f'loss: {loss.item()}')
        
        

y_hat: -2.23799991607666
loss: 128.5502471923828
y_hat: -1.5240000486373901
loss: 55.115779876708984
y_hat: -1.1500000953674316
loss: 33.0625
y_hat: -1.8300000429153442
loss: 72.76089477539062
